'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DoanhSo_ItemSub

    '''<summary>
    '''datest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datest As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''dateen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateen As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''Btok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btok As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxPivotGridExporter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGridExporter2 As Global.DevExpress.Web.ASPxPivotGrid.Export.ASPxPivotGridExporter

    '''<summary>
    '''btnXlsxExport2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXlsxExport2 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxPivotGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGrid2 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

    '''<summary>
    '''PivotGridField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField1 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField2 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField3 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField4 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField5 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField6 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField7 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField8 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField9 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField10 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField11 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField12 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField13 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField14 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField15 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField16 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField17 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''PivotGridField18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PivotGridField18 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
