'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DS_khach_hang

    '''<summary>
    '''datest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datest As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''dateen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateen As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''btnXlsxExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXlsxExport As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxComboBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox1 As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Btok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btok As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton2 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxPivotGridExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGridExporter1 As Global.DevExpress.Web.ASPxPivotGrid.Export.ASPxPivotGridExporter

    '''<summary>
    '''ASPxPivotGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

    '''<summary>
    '''fieldMaNPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldMaNPP As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTenNPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTenNPP As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldRegion As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldMaKH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldMaKH As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTenKH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTenKH As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldMaNV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldMaNV As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldHoten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldHoten As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldSldh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldSldh As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldSLHB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldSLHB As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldThanhtien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldThanhtien As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldSLKM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldSLKM As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldKhuyenmai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldKhuyenmai As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldmakhh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldmakhh As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldThang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldThang As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldnam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldnam As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource3 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''pcCreateAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcCreateAccount As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl2 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''PanelContent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent2 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''EBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EBrand As Global.DevExpress.Web.ASPxEditors.ASPxDropDownEdit

    '''<summary>
    '''ENhan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ENhan As Global.DevExpress.Web.ASPxEditors.ASPxDropDownEdit

    '''<summary>
    '''ASPmui control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPmui As Global.DevExpress.Web.ASPxEditors.ASPxDropDownEdit

    '''<summary>
    '''ASPxSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxSize As Global.DevExpress.Web.ASPxEditors.ASPxDropDownEdit

    '''<summary>
    '''ASPxloai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxloai As Global.DevExpress.Web.ASPxEditors.ASPxDropDownEdit

    '''<summary>
    '''ASPxItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxItem As Global.DevExpress.Web.ASPxEditors.ASPxDropDownEdit

    '''<summary>
    '''btCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCreate As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btCancel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancel2 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''SqlNhan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNhan As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Sqlmui control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sqlmui As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Sqlsize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sqlsize As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlItem As Global.System.Web.UI.WebControls.SqlDataSource
End Class
