'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class budget

    '''<summary>
    '''FileUpload3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload3 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ASPxButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton2 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''txtNam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNam As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxButton6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton6 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPExport As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxGridViewExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporter1 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ASPxSplitter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxSplitter2 As Global.DevExpress.Web.ASPxSplitter.ASPxSplitter

    '''<summary>
    '''ASPxRoundPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel2 As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

    '''<summary>
    '''PanelContent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent2 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''ASPxCallbackPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallbackPanel1 As Global.DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel

    '''<summary>
    '''PanelContent3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent3 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''pcCreateAccount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcCreateAccount1 As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl2 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

    '''<summary>
    '''ASPxCallbackPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallbackPanel2 As Global.DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel

    '''<summary>
    '''PanelContent4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent4 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''ggiohang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ggiohang As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''ASPxSV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxSV As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Bt_dieuChinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bt_dieuChinh As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
