'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Defail

    '''<summary>
    '''datest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datest As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''dateen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateen As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''Btok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btok As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnXlsxExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXlsxExport As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxPivotGridExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGridExporter1 As Global.DevExpress.Web.ASPxPivotGrid.Export.ASPxPivotGridExporter

    '''<summary>
    '''ASPxButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton1 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxPivotGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

    '''<summary>
    '''fieldDebcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldDebcode As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldorderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldorderDate As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldfieldForceCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldfieldForceCode As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldretailerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldretailerCode As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldorderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldorderNumber As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldproductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldproductCode As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldprice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldprice As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldorderQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldorderQuantity As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldAmount As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldItemname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldItemname As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldBrand As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldCategoryViet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldCategoryViet As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldDebname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldDebname As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldRegion As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldArea As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTenNV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTenNV As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldSd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldSd As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
End Class
