'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportConverted
    
    '''<summary>
    '''datest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datest As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit
    
    '''<summary>
    '''dateen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateen As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit
    
    '''<summary>
    '''Btok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btok As Global.DevExpress.Web.ASPxEditors.ASPxButton
    
    '''<summary>
    '''btnXlsxExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXlsxExport As Global.DevExpress.Web.ASPxEditors.ASPxButton
    
    '''<summary>
    '''ASPxPivotGridExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGridExporter1 As Global.DevExpress.Web.ASPxPivotGrid.Export.ASPxPivotGridExporter
    
    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ASPxPivotGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid
    
    '''<summary>
    '''fieldDebcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldDebcode As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldOlddebcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldOlddebcode As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldManv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldManv As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldHoten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldHoten As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldActive As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldamountdms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldamountdms As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldsodhang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldsodhang As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldAmountEVS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldAmountEVS As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fielddonhangeve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fielddonhangeve As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldthanhcong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldthanhcong As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldchuyendoi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldchuyendoi As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldDebname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldDebname As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldRegion As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldArea As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldTenNV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTenNV As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
End Class
