'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ct_donhang

    '''<summary>
    '''ngaydat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ngaydat As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''manpp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents manpp As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''tennpp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tennpp As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''tKho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tKho As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''ggiohang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ggiohang As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''txtCopied control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCopied As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dathang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dathang As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lrbp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lrbp As Global.DevExpress.Web.ASPxEditors.ASPxLabel
End Class
