'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tonkho

    '''<summary>
    '''datest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datest As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''dateen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateen As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''ASPxComboBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox1 As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Btok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btok As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnXlsxExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXlsxExport As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxPivotGridExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGridExporter1 As Global.DevExpress.Web.ASPxPivotGrid.Export.ASPxPivotGridExporter

    '''<summary>
    '''exportmdb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents exportmdb As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btgui control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btgui As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''pnlUploadMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUploadMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lnkDownloadYourFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDownloadYourFile As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxPivotGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

    '''<summary>
    '''fieldRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldRegion As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldProvince As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldArea As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldMaNPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldMaNPP As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTenNPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTenNPP As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldMaSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldMaSP As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTenSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTenSP As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldNhanSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldNhanSP As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldDVT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldDVT As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldGia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldGia As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTonDK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTonDK As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTonDKHB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTonDKHB As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTonDKKM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTonDKKM As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldNhapHB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldNhapHB As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldNhapKM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldNhapKM As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldXuatHB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldXuatHB As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldXuatKM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldXuatKM As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldXuatDHBKM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldXuatDHBKM As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTonCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTonCK As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTonCKHB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTonCKHB As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTonCKKM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTonCKKM As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
